### ISSUE TITLE
Inclusion into upstream linux

### ISSUE THREAD

**Issue by zintrepid** [cloudflare/linux#5]
Hi,

The patch you have developed ([0014-add-a-sysctl-to-enable-disable-tcp_collapse-logic.patch](https://github.com/cloudflare/linux/blob/master/patches/0014-add-a-sysctl-to-enable-disable-tcp_collapse-logic.patch)) to allow skipping TCP buffer collapse processing would be really useful to us at [MediaFire](https://github.com/mediafire) when using cloudflared.

When cloudflared proxies HTTP requests to our origin, the response for some of our APIs can be quite large (several gigabytes from our bulk download API). Unfortunately, the receive buffer for the local connection on the cloudflared server ends up being autotuned to the maximum allowed despite the default buffer size being more than adequate for the transfer speed that the remote connection (CloudFlare and ultimately the remote client) is capable of. This causes very high softirq CPU usage due to repeated TCP buffer collapse processing. The problem is so bad that we were seeing high softirq cpu utilization (>80%) any time just 2 such flows or more happen to be assigned to the same receive queue/cpu core.

We ended up reducing our global maximum receive buffer to alleviate this issue, but that has implications for the connection we have with you and any other high-throughput peers. This patch would allow us to keep our maximum receive buffers large without having to worry about TCP collapse processing.

All of this to ask: Has there been any attempt to merge this upstream? It seems from my limited experience that it should be generally applicable as tcp collapse processing for very large buffers costs quite a bit of CPU and seems geared towards saving smaller queues from packet loss due to occasional but brief backlogs. A large queue will very likely not be saved from packet loss especially considering the latency that collapse processing introduces.

Thanks!

**Comment by bompus** [comment]
Following up on this. There are now a couple of patches 0014- and 0020- which seem like good candidates for upstream. I couldn't find any info on these being submitted upstream yet, but maybe my search was incorrect. Is there any insight or update on this task?

**Comment by mabicca** [comment]
Same here, are these patches being submitted to the upstream kernel? They are really useful and it would be great to see them added. +1 here for this to happen.

**Comment by ignatk** [comment]
Hey folks,

Sorry for the late reply here. So the `0020-` patch was actually merged upstream https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=b650d953cd39

We don't plan submitting the first one as the latter one for us supersedes the first one and we think it is a better approach.
