### ISSUE TITLE
0024-Add-xtsproxy-Crypto-API-module.patch Uses and Progress

### ISSUE THREAD

**Issue by TemperedEnterprises** [cloudflare/linux#6]
I am often using cryptsetup to encrypt the entire boot drive as well as any other attached drive.

Performance is always an issue. For example on a 48TB usable RAID6 array on ARECA 1223-8i, encrypted aea-xts-64plain with XFS on top, I get about 280MiB/sec which is acceptable.

However, on the same system, with a 4TB nvme SSD (easy capable of 2000-3000 MiB/sec, i get about 180-200MiB/sec.

My question or "issue" is two fold, first, has cloudflare used this is production since ~2019? Second, has it been submitted to Linus and the Kernel team for inclusion? If not, why not?

while a fan of Cloudflare, can't say I am a fan of the fact you took over the internet world! ;P

**Comment by ignatk** [comment]
Hi,

The full history of this work is documented in https://blog.cloudflare.com/speeding-up-linux-disk-encryption/

Two patches were developed with respect to the above work: this one and https://github.com/cloudflare/linux/blob/12a61de6dd06408f4f3c27f8019beb66366e98e3/patches/0023-Add-DM_CRYPT_FORCE_INLINE-flag-to-dm-crypt-target.patch

We have used both in production, when they were developed and when the post above was written. However, further benchmarking showed that the performance improvement in dm-crypt for our workloads comes from https://github.com/cloudflare/linux/blob/12a61de6dd06408f4f3c27f8019beb66366e98e3/patches/0023-Add-DM_CRYPT_FORCE_INLINE-flag-to-dm-crypt-target.patch and this patch seemed to have no effect.

Therefore, we upstreamed the DM_CRYPT_FORCE_INLINE in https://github.com/torvalds/linux/commit/39d42fa96ba1b7d2544db3f8ed5da8fb0d5cb877 and left this patch here for historical context. Later we removed this patch from production and confirmed it didn't make the performance worse.

**Comment by TemperedEnterprises** [comment]
Thanks for getting back to me. Too bad the upstream hasn't flowed yet. Encryption is ever more important for everything.

**Comment by vans163** [comment]
Random thoughts, I really love the work Cloudflare is doing and was wondering if there is something more up to date to follow on the patches Cloudflare uses internally, as Linux is GPL licensed my understanding is all patches made internally need to be released opensource.

This repo is kind of 1 years stale and even includes patches not used anymore, I find it hard to believe in 1 years there has been only 1 new patch made?

**Comment by ignatk** [comment]
Hi,

> Linux is GPL licensed my understanding is all patches made internally need to be released opensource

Disclaimer: the following is my understanding, not a legal statement.
This is not quite the case. As we're a SaaS business, we don't distribute the kernel as part of our product. If the Linux kernel was licensed under the AGPL license, it would have been the case.

That said, Cloudflare does not have any incentive to keep any kernel patches internal only. On the contrary - it's a maintenance burden and we try to upstream as much as possible.

> I find it hard to believe in 1 years there has been only 1 new patch made?

Given the above do check out the upstream kernel repository and Cloudflare contributions: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/?qt=author&q=cloudflare.com

Most patches get upstreamed directly and never make it to this repo. As mentioned in the README here, other patches, which where not upstreamed, but might be useful would be published here. But lately the only case was this patch https://github.com/cloudflare/linux/blob/master/patches/0014-add-a-sysctl-to-enable-disable-tcp_collapse-logic.patch

We do have a small number of patches in the internal repository, but all of them are too specific to Cloudflare: for example, they patch the kernel build scripts to work better with our internal CI/CD pipeline. We don't have any internal-only secret patches, which for example improve the performance of the Linux kernel or introduce a cool new feature. Those would be either upstreamed or published here.

**Comment by vans163** [comment]
> If the Linux kernel was licensed under the AGPL license, it would have been the case.

Well I learned something today.

> Given the above do check out the upstream kernel repository and Cloudflare contributions:

Ah, a lot of BPF work, nice!

> Those would be either upstreamed or published here.

Cool, thanks for doing this.
